export {
  bestMatchSimilarity,
  cosine,
  DIFFERENTIATION_THRESHOLDS,
  type DifferentiationThresholds,
  type DifferentiationVariant,
  differentiateVariants,
  type EmbeddedVariant,
  levenshtein,
  type PairReport,
  scoreDifferentiation,
  sequenceSimilarity,
  slideText,
  worstReport,
} from "./differentiation";
export {
  getMarketByCode,
  getMarketProfile,
  listMarkets,
  type MarketProfile,
  type MarketSummary,
  UpdateMarketInput,
  updateMarket,
} from "./markets";
export {
  checkNumericFidelity,
  type ExtractedNumber,
  extractNumbers,
  findNumericMismatches,
  type NumericIssue,
  type NumericReference,
  parseAmount,
} from "./numeric-fidelity";
export {
  buildConversionTable,
  type ConversionEntry,
  convertTemperature,
  displayQuantity,
  formatNumber,
  formatQuantity,
  formatTiming,
  type MarketUnits,
  type MeasurementSystem,
  type NumberLocale,
  type Quantity,
  toImperial,
  toMetric,
  type Unit,
} from "./units";
